In [53]:
# Install Libraries
!pip3 install pandas matplotlib numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [54]:
# Import Libraries
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd

In [55]:
# Load in Data
url = 'https://raw.githubusercontent.com/Noah-Gallego/Plot-A-Thon/main/gamer_study_raw.csv'
df = pd.read_csv(url)

In [56]:
# Set Index to ID
df = df.set_index('respondent_id')
df.head()

,age,generation,gender,race_ethnicity_primary,lgbt_identification,is_player,is_parent,children_play_games,motivation_relax_or_pass_time,motivation_have_fun,...,teach_communication_likert,teach_inclusive_attitudes_likert,teach_conflict_resolution_likert,teach_leadership_likert,plays_sport_irl,plays_video_sport_version,belief_video_sport_improves_performance,discover_song_from_game,discover_show_from_game,discover_game_from_show
respondent_id,,,,,,,,,,,,,,,,,,,,,
1,26.0,Gen Z,Female,White/Caucasian,No,FALSE,False,False,0.0,0.0,...,3,5,2,5,True,False,False,False,False,False
2,63.0,Boomer,Female,Hispanic,No,TRUE,False,False,1.0,1.0,...,3,2,3,4,False,False,True,False,False,False
3,76.0,Boomer,Male,White/Caucasian,No,TRUE,False,False,0.0,1.0,...,4,5,4,2,False,False,True,False,False,False
4,34.0,Millennial,Nonbinary/Other,White/Caucasian,No,TRUE,True,True,1.0,1.0,...,4,2,5,5,False,False,True,False,False,True
5,29.0,Millennial,Male,Black/African American,No,TRUE,True,True,1.0,1.0,...,5,1,2,3,False,False,False,True,True,False

# Handle Erroneous Values and Clean! 🧹

In [57]:
# Deal with Missing Values
df['age'].unique()

array([26., 63., 76., 34., 29., 40., 57., 36., 73., 41., 64., 18., 48.,
       21., 74., 30., 27., 45., 88., 31., 67., 61., 25., 23., nan, 89.,
       32., 78., 35., 52., 65., 79., 43., 69., 59., 19., 42., 28., 68.,
       54., 84., 55., 33., 53., 56., 22., 49., 58., 66., 85., 39., 77.,
       44., 70., 71., 60., 50., 20., 72., 37., 46., 38., 90., 51., 75.,
       24., -3., 62., 47., 87., 86., 83., 81., 82., 80.])

We have an age of -3! As well as some missing values. Let's deal with those.

In [58]:
# Replace erroneous value
df = df.replace(-3, np.nan)

In [59]:
# Display Unique Values of all Numerical Columns
for col in df.columns:
  if df[col].dtype == 'int64' or df[col].dtype == 'float64':
    print(col, df[col].unique())

age [26. 63. 76. 34. 29. 40. 57. 36. 73. 41. 64. 18. 48. 21. 74. 30. 27. 45.
 88. 31. 67. 61. 25. 23. nan 89. 32. 78. 35. 52. 65. 79. 43. 69. 59. 19.
 42. 28. 68. 54. 84. 55. 33. 53. 56. 22. 49. 58. 66. 85. 39. 77. 44. 70.
 71. 60. 50. 20. 72. 37. 46. 38. 90. 51. 75. 24. 62. 47. 87. 86. 83. 81.
 82. 80.]
motivation_relax_or_pass_time [ 0.  1. nan]
motivation_have_fun [ 0.  1. nan]
plays_mobile [ 0.  1. nan]
plays_console [ 0.  1. nan]
plays_pc [ 0.  1. nan]
plays_vr [ 0. nan  1.]
att_joy_likert [4 5 3 2 1]
att_mental_stimulation_likert [5 4 3 1 2]
att_stress_relief_likert [4 5 2 3 1]
att_accessibility_likert [5 4 3 1 2]
att_cognitive_skills_likert [1 5 4 2 3]
att_bring_people_together_likert [4 5 1 3 2]
att_introduce_new_friends_likert [4 5 1 2 3]
att_educational_likert [3 5 4 2 1]
att_great_way_free_time_likert [2 1 3 4 5]
att_creative_skills_likert [5 1 2 4 3]
att_feeling_of_community_likert [5 4 2 1 3]
teach_problem_solving_likert [5 4 3 2 1]
teach_teamwork_likert [4 5 3 1 2]
teach_adaptability_likert [5 3 4 1 2]
teach_steam_likert [1 5 4 3 2]
teach_communication_likert [3 4 5 1 2]
teach_inclusive_attitudes_likert [5 2 1 4 3]
teach_conflict_resolution_likert [2 3 4 5 1]
teach_leadership_likert [5 4 2 3 1]

All other numerical columns looks good! Let's inspect the categorical ones!

In [60]:
for col in df.columns:
  if df[col].dtype == 'object':
    print(col, df[col].unique())

generation ['Gen Z' 'Boomer' 'Millennial' 'Gen X' 'Silent']
gender ['Female' 'Male' 'Nonbinary/Other' nan 'MALE ' 'femal']
race_ethnicity_primary ['White/Caucasian' 'Hispanic' 'Black/African American' 'Other' nan
 'Asian/Pacific Islander' 'Whtie' 'Native American/Alaskan']
lgbt_identification ['No' nan 'Yes' 'Prefer not to say']
is_player ['FALSE' 'TRUE' 'No' 'yes']

It appears there are several erroneous values, but intent is known. For example 'MALE ' should clearly be mapped to 'Male' and 'femal' to 'Female'. So let's clean that!

In [61]:
# Clean Gender Column by mapping 'MALE ' to 'Male' and 'femal' to 'Female'
df['gender'] = df['gender'].map({'MALE ': 'Male', 'femal': 'Female'})

# Clean Race/Ethnicity Column by Mapping 'Whtie' to 'White/Caucasian'
df['race_ethnicity_primary'] = df['race_ethnicity_primary'].map({'Whtie': 'White/Caucasian'})

# Clean is_player by mapping 'No' to FALSE and 'yes' to TRUE
df['is_player'] = df['is_player'].map({'No': False, 'yes': True})
df['is_player'] = df['is_player'].astype('bool')

# Handle Missing Values

In [63]:
df.isna().sum()

age                                          93
generation                                    0
gender                                     1447
race_ethnicity_primary                     1462
lgbt_identification                         110
                                           ...
plays_video_sport_version                     0
belief_video_sport_improves_performance       0
discover_song_from_game                       0
discover_show_from_game                       0
discover_game_from_show                       0
Length: 108, dtype: int64

In [41]:
# Loop over each column and convert booleans to 0:1
for col in df.columns:
  if df[col].dtype == 'bool':
    df[col] = df[col].astype('int')

# Conver Age to Int
df['age'] = df['age'].astype('int')

df.head()

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

array(['FALSE', 'TRUE', 'No', 'yes'], dtype=object)